/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_com_testjni_JniUtil */

#ifndef _Included_test_com_testjni_JniUtil
#define _Included_test_com_testjni_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_com_testjni_JniUtil
 * Method:    getMString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_test_com_testjni_JniUtil_getMString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
